C# Fundamentals : Task 4
Mums-Who-Code/Nayna.C.Sharp pull request #9
Opened 2022-03-22 04:00 UTC by NaynaMallick

closes #6

2022-03-22 04:09 UTC, ShriHumrudha requested changes

2022-03-22 04:09 UTC, ShriHumrudha commented on CSharpFundamentals/Set1Task4/Program.cs
> +            Program program = new Program();
Why do we need this?

2022-03-22 04:09 UTC, ShriHumrudha commented on CSharpFundamentals/Set1Task4/Program.cs
> +﻿namespace Set1Task3
Print the values of a, b, and c after every arithmetic operation. Here I see only the value of c and + *.

2022-03-25 02:38 UTC, NaynaMallick commented on CSharpFundamentals/Set1Task4/Program.cs
> +﻿namespace Set1Task3
resolved

2022-03-25 02:38 UTC, NaynaMallick commented on CSharpFundamentals/Set1Task4/Program.cs
> +            Program program = new Program();
resolved

2022-03-28 01:10 UTC, ShriHumrudha requested changes

2022-03-28 01:10 UTC, ShriHumrudha commented on CSharpFundamentals/Set1Task4/Program.cs
>              Console.WriteLine("Value of (++a)*(++b) = " + c2);
The problem states to increment a and decrement b at every step.

2022-03-28 15:16 UTC, NaynaMallick commented on CSharpFundamentals/Set1Task4/Program.cs
> +            int c1 = problemAddition(a, b);
fixed

2022-03-28 15:17 UTC, NaynaMallick commented on CSharpFundamentals/Set1Task4/Program.cs
>              Console.WriteLine("Value of (++a)*(++b) = " + c2);
fixed

2022-03-28 22:42 UTC, ShriHumrudha approved these changes

2022-03-28 22:43 UTC, merged